load data_set_model2.mat;
S=1;
data_set=data_set_model{2};
data_set=data_set(1:60000,:);
N=6;
alphabet=7;
%model_order=size(data_set_model{5},1);
g_alphabet=[2,2,2];
M=size(data_set_model{6},1);
array_of_sizes=data_set_model{7}(:,2);
fld=data_set_model{7}(:,3);
max_iterations=2000; epsilon=2*10^-4;
tries=1; threshold=0.04;
model_order=8;
param_accuracy=zeros(S,1);
kld_accuracy=zeros(S,1);
log_likelihood=zeros(S,max_iterations./10+1);
iter=zeros(S,max_iterations./10+1);
lambda1=data_set_model{5};
b_matrices1=data_set_model{6};
c_tensors1=data_set_model{7}(:,1);
N=size(data_set,2);
[array_of_sizes,fld] = find_fld(data_set,alphabet,model_order,N,epsilon,max_iterations,tries,threshold);